CREATE TABLE  "BABYNAME"
   (	
    "ID" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"MEANING" VARCHAR2(4000), 
	"SEX" VARCHAR2(4000), 
	"RELIGION" VARCHAR2(4000), 
	 CONSTRAINT "EBABYNAME_PK" PRIMARY KEY ("ID") ENABLE
);

CREATE SEQUENCE SEQ_BABYNAME
START WITH 4
INCREMENT BY 1
MAXVALUE 99999999
MINVALUE 1
NOCYCLE;

CREATE OR REPLACE TRIGGER baby_name_bir 
BEFORE INSERT ON BABYNAME
FOR EACH ROW

BEGIN
  SELECT SEQ_BABYNAME.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;


Insert into SYSTEM.BABYNAME (ID,NAME,MEANING,SEX,RELIGION) values (1,'abhishek','Tilak','Boy','Hindu');
Insert into SYSTEM.BABYNAME (ID,NAME,MEANING,SEX,RELIGION) values (2,'ramesh','God','Boy','Hindu');
Insert into SYSTEM.BABYNAME (ID,NAME,MEANING,SEX,RELIGION) values (3,'Raju','Innocent','Boy','Hindu');
commit;